export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES';
export const FETCH_REPOSITORIES_FULFILLED = 'FETCH_REPOSITORIES_FULFILLED';
export const FETCH_REPOSITORIES_PENDING = 'FETCH_REPOSITORIES_PENDING';